### ISSUE TITLE
ERROR: Body has already been consumed

### ISSUE THREAD

**Issue by nexhero** [holepunchto/bare-fetch#12]
I followed the code example, when I call res.json() or res.text(); I got `Body has already been consumed`

**Comment by kasperisager** [comment]
Are all your dependencies up to date?

**Comment by kasperisager** [comment]
In particular, make sure you're on `streamx` v2.21.1 which has this fix: https://github.com/mafintosh/streamx/commit/d255604e5ded6fb018b76ae3bdd4a764e5726d00

**Comment by nexhero** [comment]
installing streamx 2.21.1 fixed the issue
